# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 4.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
  SuggestExtensions: false

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-thread_safety
  - rubocop-rubycw

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/ContextWording:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/NoExpectationExample:
  AllowedPatterns:
  - ^assert_
  - ^expect_
  - ^wait(_for)?$

Rails/Output:
  Exclude:
    - 'config/initializers/*'

Rails/Exit:
  Exclude:
    - 'config/initializers/*'

